# Generated by Django 4.2.3 on 2023-12-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-fecha',)},
        ),
    ]
